server:
  port: 8082

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 10

  mail:
    host: smtp.msndr.net
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

notification:
  email:
    from: ${MAIL_USERNAME}
    subject:
      user-created: "Добро пожаловать!"
      user-deleted: "Ваш аккаунт удален"
    templates:
      welcome: "Привет, %s! Добро пожаловать в наше приложение."
      goodbye: "Ваш аккаунт был успешно удален."

  retry:
    max-attempts: 3
    delay-ms: 1000

logging:
  level:
    org.example.notification: DEBUG
    org.springframework.kafka: INFO
    org.springframework.mail: DEBUG