server:
  port: 8081

spring:
  application:
    name: user-service


  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: password

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

spring.kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    group-id: user-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

user:
  validation:
    email-regex: "^[A-Za-z0-9+_.-]+@(.+)$"
    min-name-length: 2
    max-name-length: 50

  security:
    password:
      min-length: 8
      require-special-char: true
      require-number: true

logging:
  level:
    org.example.user: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG